"""
Task data model and Status enum for the Todo Console Application.

[Task]: T005, T006
[From]: specs/001-todo-console-app/data-model.md
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class Status(Enum):
    """
    Task status enumeration.

    Represents the current state of a task in the todo system.

    Attributes:
        PENDING: Task is created but not yet completed (default state)
        COMPLETE: Task has been marked as finished

    [Task]: T005
    [From]: specs/001-todo-console-app/data-model.md
    """
    PENDING = "Pending"
    COMPLETE = "Complete"


@dataclass(frozen=True)
class Task:
    """
    Represents a single todo item.

    A Task is an immutable entity representing a todo item with a unique ID,
    title, optional description, and current status.

    Attributes:
        id: Unique numeric identifier (auto-generated by system, immutable)
        title: Required task description (non-empty, max 500 characters)
        description: Optional additional details about the task (max 500 characters)
        status: Current task state (Pending or Complete)

    Design Decisions:
        - frozen=True: Makes Task immutable after creation to prevent accidental
          modifications and ensure thread-safety for future concurrent access
        - Updates are performed by creating new Task instances in the service layer

    [Task]: T006
    [From]: specs/001-todo-console-app/data-model.md
    """
    id: int
    title: str
    description: Optional[str]
    status: Status
